re-download bootstrap script due to permission error
> Run actions/download-artifact@v3
Starting download for prefix_stage3
Directory structure has been setup for the artifact
Total number of files that will be downloaded: 2
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/bootstrap-prefix.sh'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/bootstrap-prefix.sh'
}